
pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'echo "Building..."'
            }
        }
    }

    post {
        success {
            emailext (
                to: 'mehtakawal21@gmail.com',
                subject: "SUCCESS: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                body: "The build succeeded! Logs: ${env.BUILD_URL}"
            )
            slackSend (
                channel: '#jenkins-pipeline-notification',
                message: "SUCCESS: ${env.JOB_NAME} #${env.BUILD_NUMBER} (${env.BUILD_URL})",
                teamDomain: 'team-aptgetswag'
            )
        }
        failure {
            emailext (
                to: 'mehtakawal21@gmail.com',
                subject: "FAILED: ${env.JOB_NAME} #${env.BUILD_NUMBER}",
                body: "The build failed! Logs: ${env.BUILD_URL}"
            )
            slackSend (
                channel: '#jenkins-pipeline-notification',
                message: "FAILED: ${env.JOB_NAME} #${env.BUILD_NUMBER} (${env.BUILD_URL})",
                teamDomain: 'team-aptgetswag'
            )
        }
    }
}
